language: ruby
rvm:
- 2.2
install:
- nvm install 6.2
- npm set progress=false && npm i bower -g && bower install
- bundle install
script:
- "bundle exec jekyll build"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
